/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaCodes;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Date;  

/**
 *
 * @author Maryam
 */
public class Diary extends javax.swing.JFrame {
    
    Calendar c = new GregorianCalendar();
    String date;
    public Diary() {
        initComponents();
        Date();
    }
    
    public String Time(){
        int second = c.get(Calendar.SECOND);
        int minute = c.get(Calendar.MINUTE);
        int hour = c.get(Calendar.HOUR);
        
        String time = hour+":"+minute+":"+second;
        return time;
    }
    
    public void Date(){
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        Date d = new Date();
        date = formatter.format(d);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mimmy_lbl = new javax.swing.JLabel();
        date_lbl = new javax.swing.JLabel();
        diary_sp = new javax.swing.JScrollPane();
        diary_ta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        galaxy_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(890, 520));
        setMinimumSize(new java.awt.Dimension(890, 520));
        setResizable(false);
        setSize(new java.awt.Dimension(890, 520));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("History");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(777, 470, -1, 30));

        mimmy_lbl.setFont(new java.awt.Font("Rage Italic", 1, 40)); // NOI18N
        mimmy_lbl.setForeground(new java.awt.Color(255, 255, 255));
        mimmy_lbl.setText("CHAPTER OF MY LIFE!");
        getContentPane().add(mimmy_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 450, 70));

        date_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        date_lbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(date_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 160, 30));

        diary_ta.setBackground(new java.awt.Color(51, 0, 51));
        diary_ta.setColumns(20);
        diary_ta.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        diary_ta.setForeground(new java.awt.Color(255, 255, 255));
        diary_ta.setRows(5);
        diary_ta.setCaretColor(new java.awt.Color(255, 255, 255));
        diary_ta.setSelectedTextColor(new java.awt.Color(255, 102, 102));
        diary_ta.setSelectionColor(new java.awt.Color(255, 255, 255));
        diary_sp.setViewportView(diary_ta);

        getContentPane().add(diary_sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 840, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dear Mimmy,");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 30));

        jButton3.setBackground(new java.awt.Color(51, 0, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Delete");
        jButton3.setBorder(null);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 80, 30));

        jButton4.setBackground(new java.awt.Color(51, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.setBorder(null);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 80, 30));

        galaxy_lbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage.jpg"))); // NOI18N
        getContentPane().add(galaxy_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        diary_ta.requestFocusInWindow();
        date_lbl.setText(date);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_lbl;
    private javax.swing.JScrollPane diary_sp;
    private javax.swing.JTextArea diary_ta;
    private javax.swing.JLabel galaxy_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mimmy_lbl;
    // End of variables declaration//GEN-END:variables
}
